### ISSUE TITLE
[Bug] User Settings are now covered due to the new custom status menu

### ISSUE THREAD

**Issue by BLANKE1** [Juby210/game-activity-toggle#10]
![image](https://user-images.githubusercontent.com/68296465/169676213-d6017733-d59b-4856-92cd-9f9383e89299.png)

**Comment by Iucism** [comment]
+1

**Comment by devicarus** [comment]
Some hover effect like this would probably be the best solution?
![game-activity-toggle-fix](https://user-images.githubusercontent.com/34186403/180619751-ba5532b6-bced-4693-87e9-800507b97915.gif)

```css
.avatarWrapper-1B9FTW.withTagAsButton-OsgQ9L {
  min-width: 0;
  transition: 0.2s;
}

.avatarWrapper-1B9FTW.withTagAsButton-OsgQ9L:hover {
  min-width: 120px;
  transition: 0.2s;
}
```

How about a toggle in the plugin settings to apply some fix like this?
